ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  issuer: "jwt-issuer"
  time: 3600000000
  secret: "jwt-secret"
db:
  mongo:
    user: $DB_USER
    password: $DB_PASSWORD
    url: $DB_URL
    database:
      name: $DB_NAME